<?php

/** 
 * Implements hook_permission().
 */ 
function easyloan_permission() {
  return array(
    'auditor permission' => array(
      'title'       => t('注册用户借款审核员权限'),
      'description' => t('注册用户借款审核员：网站初级管理员，负责审核网站新注册用户资料、抵押借款申请资料、浏览用户资料、获取应付款账户（投资用户）及金额列表，获取应还款账户（借款用户）及金额列表，浏览抵押借款欠款用户及金额列表'),
    ),
    'accountant permission' => array(
      'title'       => t('财务人员权限'),
      'description' => t('财务人员：网站中级管理员，除具备所有初级管理员的权限外，负责更新用户（借款、投资）账户资金状态，包括提现后资金状态、借款成功后资金状态等等'),
    ),
    'manager permission' => array(
      'title'       => t('信息及用户管理员权限'),
      'description' => t('信息及用户管理员：网站高级管理员，除具备所有中级管理员的权限外，负责管理网站信息（发布、修改、删除），管理投资产品（发布、修改、删除），最终审核用户、禁止用户'),
    ),
  );
}

/**
* Implementation of hook_menu().
*/
function easyloan_menu() { 
  // api function calls
  $items['api/m_owned_user'] = array(
    'page callback'   => 'manage_owned_user', 
    'access callback' => 'authenticated_access',
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/manage_owned_user.php',
  );
  $items['api/m_owned_users'] = array(
    'page callback'   => 'manage_owned_users', 
    'access callback' => 'authenticated_access',
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/manage_owned_users.php',
  );
  $items['api/m_notices'] = array(
    'page callback'   => 'manage_notices', 
    'access callback' => 'authenticated_access',
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/manage_notices.php',
  );
  $items['api/chinabank_receive'] = array(
    'page callback'   => 'chinabank_receive', 
    'access callback' => TRUE,
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/chinabank_receive.php',
  );
  $items['api/transaction_summary'] = array(
    'page callback'   => 'transaction_summary', 
    'access callback' => 'authenticated_access',
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/account_transaction_summary.php',
  );
  $items['api/transactions'] = array(
    'page callback'   => 'transactions', 
    'access callback' => 'authenticated_access',
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/account_transactions.php',
  );
  $items['api/myinvestments'] = array(
    'page callback'   => 'myinvestments', 
    'access callback' => 'authenticated_access',
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/account_investments.php',
  );
  $items['api/investments'] = array(
    'page callback'   => 'investments', 
    'access callback' => TRUE,
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/investments.php',
  );
  $items['api/invest'] = array(
    'page callback'   => 'invest', 
    'access callback' => 'authenticated_access',
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/invest.php',
  );
  $items['api/investment'] = array(
    'page callback'   => 'investment', 
    'access callback' => TRUE,
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/investment.php',
  );
  $items['api/m_set_investment'] = array(
    'page callback'   => 'manage_set_investment', 
    'access callback' => 'authenticated_access',
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/manage_set_investment.php',
  );
  $items['api/m_investments'] = array(
    'page callback'   => 'manage_investments', 
    'access callback' => 'authenticated_access',
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/manage_investments.php',
  );
  $items['api/m_set_loan'] = array(
    'page callback'   => 'manage_set_loan', 
    'access callback' => 'authenticated_access',
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/manage_set_loan.php',
  );
  $items['api/m_loans'] = array(
    'page callback'   => 'manage_loans', 
    'access callback' => 'authenticated_access',
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/manage_loans.php',
  );
  $items['api/m_loan_applications'] = array(
    'page callback'   => 'manage_loan_applications', 
    'access callback' => 'authenticated_access',
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/manage_loan_applications.php',
  );
  $items['api/loanapp'] = array(
    'page callback'   => 'loanapp', 
    'access callback' => 'authenticated_access',
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/account_loan_application.php',
  );
  $items['api/loan'] = array(
    'page callback'   => 'loan', 
    'access callback' => 'authenticated_access',
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/account_loan.php',
  );
  $items['api/loans'] = array(
    'page callback'   => 'loans', 
    'access callback' => 'authenticated_access',
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/account_loans.php',
  );
  $items['api/apply'] = array(
    'page callback'   => 'apply', 
    'access callback' => 'authenticated_access',
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/apply.php',
  );
  $items['api/m_set_withdraw'] = array(
    'page callback'   => 'manage_set_withdraw', 
    'access callback' => 'authenticated_access',
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/manage_set_withdraw.php',
  );
  $items['api/m_withdraws'] = array(
    'page callback'   => 'manage_withdraws', 
    'access callback' => 'authenticated_access',
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/manage_withdraws.php',
  );
  $items['api/banks'] = array(
    'page callback'   => 'account_banks', 
    'access callback' => 'authenticated_access',
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/account_banks.php',
  );
  $items['api/withdraw'] = array(
    'page callback'   => 'account_withdraw', 
    'access callback' => 'authenticated_access',
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/account_withdraw.php',
  );
  $items['api/recharge'] = array(
    'page callback'   => 'account_recharge', 
    'access callback' => 'authenticated_access',
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/account_recharge.php',
  );
  $items['api/params'] = array(
    'page callback'   => 'params', 
    'access callback' => 'authenticated_access',
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/params.php',
  );
  $items['api/basic'] = array(
    'page callback'   => 'account_info', 
    'access callback' => 'authenticated_access',
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/account_info.php',
  );
  $items['api/security'] = array(
    'page callback'   => 'account_security', 
    'access callback' => 'authenticated_access', 
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/account_security.php',
  );
  $items['api/findpwd'] = array(
    'page callback'   => 'account_findpwd', 
    'access callback' => TRUE, 
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/account_findpwd.php',
  );
  $items['api/manage_user'] = array(
    'page callback'   => 'manage_user', 
    'access callback' => 'authenticated_access', 
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/manage_user.php',
  );
  $items['api/manage_users'] = array(
    'page callback'   => 'manage_users', 
    'access callback' => 'authenticated_access', 
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/manage_users.php',
  );
  $items['api/account_status'] = array(
    'page callback'   => 'account_status', 
    'access callback' => 'authenticated_access', 
    'type'            => MENU_NORMAL_ITEM, 
    'file'            => 'api/account_status.php',
  );

  // recharge bank
  $items['chinabank/send'] = array(
    'title'           => t('在线支付接口'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('chinabank_send'), 
    'access callback' => 'authenticated_access', 
    'type'            => MENU_NORMAL_ITEM, 
  );

  // real menus
  $items['invest'] = array(
    'title'           => t('我要投资'), 
    'page callback'   => 'menu_invest', 
    'page arguments'  => array(1), // if of the investing page
    'access callback' => TRUE, 
    'type'            => MENU_NORMAL_ITEM, 
  );
  $items['borrow'] = array( 
    'title'           => t('我要借款'), 
    'page callback'   => 'menu_borrow', 
    'access callback' => TRUE, 
    'type'            => MENU_NORMAL_ITEM, 
  );
  $items['borrow/estate'] = array( 
    'title'           => t('房屋商铺抵押'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('borrow_estate'), 
    'access callback' => TRUE, 
    'type'            => MENU_NORMAL_ITEM, 
  );
  $items['borrow/estate/apply'] = array(
    'title'           => t('房屋商铺抵押申请'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('borrow_estate_apply'), 
    'access callback' => 'authenticated_access', 
    'type'            => MENU_NORMAL_ITEM, 
  );
  $items['borrow/car'] = array(
    'title'           => t('机动车抵押'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('borrow_car'),
    'access callback' => TRUE, 
    'type'            => MENU_NORMAL_ITEM, 
  );
  $items['borrow/car/apply'] = array( 
    'title'           => t('机动车抵押申请'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('borrow_car_apply'),
    'access callback' => 'authenticated_access', 
    'type'            => MENU_NORMAL_ITEM, 
  );
  $items['borrow/gold'] = array(
    'title'           => t('黄金抵押'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('borrow_gold'),
    'access callback' => TRUE, 
    'type'            => MENU_NORMAL_ITEM, 
  );
  $items['borrow/gold/apply'] = array(
    'title'           => t('黄金抵押申请'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('borrow_gold_apply'),
    'access callback' => 'authenticated_access', 
    'type'            => MENU_NORMAL_ITEM, 
  );
  $items['borrow/credit'] = array(
    'title'           => t('信用贷'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('borrow_credit'),
    'access callback' => TRUE, 
    'type'            => MENU_NORMAL_ITEM, 
  );
  $items['borrow/credit/apply'] = array( 
    'title'           => t('信用贷申请'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('borrow_credit_apply'),
    'access callback' => 'authenticated_access', 
    'type'            => MENU_NORMAL_ITEM, 
  );
  $items['borrow/else'] = array(
    'title'           => t('其他抵押'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('borrow_else'),
    'access callback' => TRUE, 
    'type'            => MENU_NORMAL_ITEM, 
  );
  $items['borrow/else/apply'] = array(
    'title'           => t('其他抵押申请'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('borrow_else_apply'),
    'access callback' => 'authenticated_access', 
    'type'            => MENU_NORMAL_ITEM, 
  );
  $items['notfound'] = array( 
    'title'           => t('找不到该页面'), 
    'page callback'   => 'menu_notfound', 
    'access callback' => TRUE, 
    'type'            => MENU_NORMAL_ITEM, 
  );

  /*******************个人账户页面菜单 begin*************************/
  $items['capital_management'] = array( 
    'title'           => t('资金管理'), 
    'page callback'   => 'drupal_goto', 
    'page arguments'  => array('capital_management/deals', array()), 
    'access callback'   => 'authenticated_access', 
    'type'            => MENU_NORMAL_ITEM,
    'expanded'        => TRUE,
    'menu_name'       => 'easyloan_account',
    'weight'          => '0'
  );

  $items['capital_management/deals'] = array( 
    'title'           => t('交易记录'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('account_capital'),
    'access callback'   => 'authenticated_access', 
    'type'            => MENU_NORMAL_ITEM, 
    'menu_name'       => 'easyloan_account',
    'weight'          => '10'
  );
  $items['capital_management/recharge'] = array( 
    'title'           => t('充值'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('account_recharge'),
    'access callback'   => 'authenticated_access', 
    'type'            => MENU_NORMAL_ITEM, 
    'menu_name'       => 'easyloan_account',
    'weight'          => '20'
  );
  $items['capital_management/withdraw'] = array( 
    'title'           => t('提现'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('account_withdraw'),
    'access callback'   => 'authenticated_access', 
    'type'            => MENU_NORMAL_ITEM, 
    'menu_name'       => 'easyloan_account',
    'weight'          => '30'
  );
  $items['invest_management'] = array(
    'title'           => t('理财管理'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('account_myinvestment'),
    'access callback'   => 'authenticated_access', 
    'type'            => MENU_NORMAL_ITEM, 
    'menu_name'       => 'easyloan_account',
    'weight'          => '10'
  );
  $items['loan_management'] = array( 
    'title'           => t('借款管理'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('account_myloan'),
    'access callback'   => 'authenticated_access', 
    'type'            => MENU_NORMAL_ITEM, 
    'menu_name'       => 'easyloan_account',
    'weight'          => '20'
  );
  $items['loan_view'] = array( 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('account_loanview'),
    'access callback'   => 'authenticated_access', 
    'type'            => MENU_NORMAL_ITEM, 
  );
  $items['loanapp_view'] = array( 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('account_loanappview'),
    'access callback'   => 'authenticated_access', 
    'type'            => MENU_NORMAL_ITEM, 
  );

  $items['account_management'] = array( 
    'title'           => t('账户管理'), 
    'page callback'   => 'drupal_goto', 
    'page arguments'  => array('account_management/basicinfo', array()), 
    'access callback'   => 'authenticated_access', 
    'type'            => MENU_NORMAL_ITEM, 
    'expanded'        => TRUE,
    'menu_name'       => 'easyloan_account',
    'weight'          => '30'
  );

  $items['account_management/basicinfo'] = array( 
    'title'           => t('个人基本信息'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('account_basicinfo'),
    'access callback'   => 'authenticated_access', 
    'type'            => MENU_NORMAL_ITEM, 
    'menu_name'       => 'easyloan_account',
    'weight'          => '0'
  );
  $items['account_management/security'] = array( 
    'title'           => t('安全信息'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('account_security'),
    'access callback'   => 'authenticated_access', 
    'type'            => MENU_NORMAL_ITEM, 
    'menu_name'       => 'easyloan_account',
    'weight'          => '10'
  );
  $items['account_management/bankcard'] = array( 
    'title'           => t('银行卡信息'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('account_bankcard'),
    'access callback'   => 'authenticated_access', 
    'type'            => MENU_NORMAL_ITEM, 
    'menu_name'       => 'easyloan_account',
    'weight'          => '20'
  );

  $items['management'] = array( 
    'title'           => t('好易贷管理'), 
    'page callback'   => 'drupal_goto', 
    'page arguments'  => array('management/users', array()), 
    'access callback' => 'management_access',
    'type'            => MENU_NORMAL_ITEM, 
    'expanded'        => TRUE,
    'menu_name'       => 'easyloan_account',
    'weight'          => '40'
  );

  $items['management/users'] = array( 
    'title'           => t('用户管理'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('account_management', 2),
    'access arguments' => array('manager permission'),
    'type'            => MENU_NORMAL_ITEM, 
    'menu_name'       => 'easyloan_account',
    'weight'          => '0'
  );
  $items['management/%/capital'] = array(
    'title'           => t('用户管理交易查看'), 
    'page callback'   => 'menu_account_management_capital', 
    'page arguments'  => array(1, 2, 3),
    'access arguments' => array('auditor permission'),
    'type'            => MENU_NORMAL_ITEM, 
    'menu_name'       => 'easyloan_account',
    'weight'          => '5'
  );
  $items['management/accountsindebt'] = array( 
    'title'           => t('欠款账户'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('management_accountsindebt', 2),
    'access arguments' => array('accountant permission'),
    'type'            => MENU_NORMAL_ITEM, 
    'menu_name'       => 'easyloan_account',
    'weight'          => '10'
  );
  $items['management/applications'] = array(
    'title'           => t('借款审核'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('management_applications'),
    'access arguments' => array('auditor permission'),
    'type'            => MENU_NORMAL_ITEM, 
    'menu_name'       => 'easyloan_account',
    'weight'          => '15'
  );
  $items['management/loans'] = array( 
    'title'           => t('借款项目'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('management_loans', 2),
    'access arguments' => array('accountant permission'),
    'type'            => MENU_NORMAL_ITEM, 
    'menu_name'       => 'easyloan_account',
    'weight'          => '20'
  );
  $items['management/investments'] = array( 
    'title'           => t('投资产品'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('management_investments', 2),
    'access arguments' => array('manager permission'),
    'type'            => MENU_NORMAL_ITEM, 
    'menu_name'       => 'easyloan_account',
    'weight'          => '25'
  );
  $items['management/withdrawappl'] = array(
    'title'           => t('提现申请'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('management_withdrawappl', 2),
    'access arguments' => array('accountant permission'),
    'type'            => MENU_NORMAL_ITEM, 
    'menu_name'       => 'easyloan_account',
    'weight'          => '30'
  );
  $items['management/settings'] = array( 
    'title'           => t('通知设置'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('account_settings'),
    'access arguments' => array('accountant permission'),
    'type'            => MENU_NORMAL_ITEM, 
    'menu_name'       => 'easyloan_account',
    'weight'          => '35'
  );
  /*******************个人账户页面菜单 end*************************/

  /*******************帮助中心 begin*************************/
  /*
  $items['help'] = array( 
    'page callback'   => 'easyloan_goto', 
    'page arguments'  => array('help/help'), 
    'access callback' => TRUE, 
    'type'            => MENU_NORMAL_ITEM, 
  );*/
  $items['help/help'] = array(
    'title'           => t('名词解释'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('help_help'),
    'access callback' => TRUE, 
    'type'            => MENU_NORMAL_ITEM, 
    'menu_name'       => 'easyloan_help',
    'weight'          => '0'
  );
  $items['help/intro'] = array(
    'title'           => t('平台介绍'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('help_intro'),
    'access callback' => TRUE, 
    'type'            => MENU_NORMAL_ITEM, 
    'menu_name'       => 'easyloan_help',
    'weight'          => '10'
  );
  $items['help/fee'] = array(
    'title'           => t('利息和费用'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('help_fee'),
    'access callback' => TRUE, 
    'type'            => MENU_NORMAL_ITEM, 
    'menu_name'       => 'easyloan_help',
    'weight'          => '20'
  );
  $items['help/borrow'] = array(
    'title'           => t('我要借款'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('help_borrow'),
    'access callback' => TRUE, 
    'type'            => MENU_NORMAL_ITEM, 
    'menu_name'       => 'easyloan_help',
    'weight'          => '30'
  );
  $items['help/invest'] = array(
    'title'           => t('我要投资'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('help_invest'),
    'access callback' => TRUE, 
    'type'            => MENU_NORMAL_ITEM, 
    'menu_name'       => 'easyloan_help',
    'weight'          => '40'
  );
  $items['help/account'] = array(
    'title'           => t('好易贷账户'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('help_account'),
    'access callback' => TRUE, 
    'type'            => MENU_NORMAL_ITEM, 
    'menu_name'       => 'easyloan_help',
    'weight'          => '50'
  );

  /*******************帮助中心 end*************************/

  /*******************新手指引 begin***********************/
  $items['guide/guide'] = array(
    'title'           => t('我要投资'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('guide_guide'),
    'access callback' => TRUE, 
    'type'            => MENU_NORMAL_ITEM, 
    'menu_name'       => 'easyloan_guide',
    'weight'          => '0'
  );
  $items['guide/borrow'] = array(
    'title'           => t('我要借款'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('guide_borrow'),
    'access callback' => TRUE, 
    'type'            => MENU_NORMAL_ITEM, 
    'menu_name'       => 'easyloan_guide',
    'weight'          => '10'
  );
  $items['guide/security'] = array( 
    'title'           => t('安全保障'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('guide_security'),
    'access callback' => TRUE, 
    'type'            => MENU_NORMAL_ITEM,
    'menu_name'       => 'easyloan_guide', 
    'weight'          => '20'
  );
  /*******************新手指引 end*************************/

  /*******************关于我们 begin***********************/
  $items['about/news'] = array( 
    'title'           => t('最新动态'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('about_news', 2),
    'access callback' => TRUE, 
    'type'            => MENU_NORMAL_ITEM, 
    'menu_name'       => 'easyloan_about', 
    'weight'          => '10'
  );
  $items['about/notices'] = array( 
    'title'           => t('网站公告'), 
    'page callback'   => 'menu_callback', 
    'page arguments'  => array('about_notices'),
    'access callback' => TRUE, 
    'type'            => MENU_NORMAL_ITEM, 
    'menu_name'       => 'easyloan_about', 
    'weight'          => '20'
  );
  $items['about/company'] = array( 
    'title'           => t('公司简介'), 
    'page callback' => 'node_page_view',
    'page arguments' => array(entity_load('node', false, array('title' => '公司简介', 'type' => 'normal'))),
    'access callback' => TRUE, 
    'type'            => MENU_NORMAL_ITEM, 
    'menu_name'       => 'easyloan_about', 
    'weight'          => '0'
  );
  $items['about/invite'] = array( 
    'title'           => t('招贤纳士'), 
    'page callback' => 'node_page_view',
    'page arguments' => array(entity_load('node', false, array('title' => '招贤纳士', 'type' => 'normal'))),
    'access callback' => TRUE, 
    'type'            => MENU_NORMAL_ITEM, 
    'menu_name'       => 'easyloan_about', 
    'weight'          => '30'
  );
  $items['about/contact'] = array( 
    'title'           => t('联系我们'), 
    'page callback' => 'node_page_view',
    'page arguments' => array(entity_load('node', false, array('title' => '联系我们', 'type' => 'normal'))),
    'access callback' => TRUE, 
    'type'            => MENU_NORMAL_ITEM, 
    'menu_name'       => 'easyloan_about', 
    'weight'          => '40'
  );
  
  $items['exists'] = array( 
    'page callback'   => 'easyloan_exists',
    'access callback' => TRUE, 
    'type'            => MENU_NORMAL_ITEM, 
  );
  $items['captcha_check'] = array(
    'page callback'   => 'captcha_check',
    'access callback' => TRUE, 
    'type'            => MENU_NORMAL_ITEM, 
  );
  
  /*******************关于我们 end***********************/
  return $items; 
} 

function easyloan_exists(){

  $name = $_POST['name'];

  $user = user_load_by_name($name);
  if(!$user){
    // User doesn't exist
    echo 'true';
  } 
  else {
    // User exists
    echo 'false';
  }
}

function captcha_check(){ 
  $solution = $_POST['captcha'];
  $csid = $_POST['sid'];
  $token = $_POST['token'];

  $result = db_select('captcha_sessions', 'cs')
    ->fields('cs')
    ->condition('csid', $csid)
    ->condition('token', $token)
    ->condition('solution', $solution)
    ->range(0, 1)
    ->execute()
    ->rowCount();

  if($result){
    // User doesn't exist
    echo 'true';
  } 
  else {
    // User exists
    echo 'false';
  }
}

/*
* Inplementation of the block_info hook
*/
function easyloan_block_info() {
  $blocks['footer'] = array(
    'info'   => t('好易贷的页脚上部'),
    'cache'  => DRUPAL_CACHE_GLOBAL,
    'status' => 1,
    'region' => 'footer',
  );
  $blocks['bottom'] = array(
    'info'   => t('好易贷的页脚底部'),
    'cache'  => DRUPAL_CACHE_GLOBAL,
    'status' => 1,
    'region' => 'bottom',
  );
  $blocks['intro'] = array(
    'info'       => t('好易贷的首页的功能介绍'),
    'cache'      => DRUPAL_NO_CACHE,
    'status'     => 1,
    'weight'     => 0,
    'region'     => 'content_top',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages'      => '<front>',
  );
  $blocks['topnotice'] = array(
    'info'       => t('好易贷的首页的通知'),
    'cache'      => DRUPAL_NO_CACHE,
    'status'     => 1,
    'weight'     => 5,
    'region'     => 'content_top',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages'      => '<front>',
  );
  $blocks['investlist'] = array(
    'info'       => t('好易贷的首页的投资列表'),
    'cache'      => DRUPAL_NO_CACHE,
    'status'     => 1,
    'weight'     => 10,
    'region'     => 'content_top',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages'      => '<front>',
  );
  $blocks['newslist'] = array(
    'info'       => t('好易贷的首页的最新动态列表'),
    'cache'      => DRUPAL_NO_CACHE,
    'status'     => 1,
    'weight'     => 15,
    'region'     => 'content_top',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages'      => '<front>',
  );
  $blocks['header'] = array(
    'info'   => t('好易贷的页面头部'),
    'cache'  => DRUPAL_NO_CACHE,
    'status' => 1,
    'region' => 'header',
  );
  return $blocks;
}

function easyloan_block_view($delta = ''){
  $block = array();
  switch($delta){
    case 'footer':
      $block['subject'] = t('');
      $block['content'] = array('#title' => '', );
      return $block;
    case 'header':
      $block['subject'] = t('');
      $block['content'] = array('#title' => '', );
      return $block;
    case 'bottom':
      $block['subject'] = t('');
      $block['content'] = array('#title' => '', );
      return $block;
    case 'intro':
      $block['subject'] = t('');
      $block['content'] = array('#title' => '', );
      return $block;
    case 'topnotice': 
      $block['subject'] = t(''); 
      $block['content'] = array('#title' => '', ); 
      $block['params'] = array(); 

      // get the latest notice 
      $query = "SELECT nid, title, notice_date_value, body_value, notice_publisher_value 
                FROM node AS A
                LEFT OUTER JOIN field_data_body AS B ON A.nid = B.entity_id
                LEFT OUTER JOIN field_data_notice_date AS C ON A.nid = C.entity_id
                LEFT OUTER JOIN field_data_notice_publisher AS D ON A.nid = D.entity_id
                WHERE TYPE = 'notice'
                ORDER BY nid DESC LIMIT 0, 1";

      // get the latest notice if exists
      $result = db_query($query)->fetchObject();

      if ($result){
        $nid = $result->nid;
        $title = $result->title;
        $body = $result->body_value;
        $publisher = $result->notice_publisher_value;

        $date_array = date_parse($result->notice_date_value);
        $time = mktime(0, 0, 0, $date_array['month'], $date_array['day'], $date_array['year']);
        $date = date("Y-m-d", $time); 
        $date1 = date("Y年m月d日", $time); 

        $block['params'] = array(
                            'title' => $title,
                            'date' => $date,
                            'date1' => $date1,
                            'body' => $body,
                            'publisher' => $publisher,
                            );
      }
      return $block;
    case 'investlist':
      $block['subject'] = t('');
      $block['content'] = array('#title' => '', );
      return $block;
    case 'newslist':
      $block['subject'] = t('asdfasdf');
      $block['content'] = array('#title' => '', );
      $block['params'] = array(); 

      // get the latest 4 news  
      $query = "SELECT nid, title, news_date_value 
                FROM node AS A
                LEFT OUTER JOIN field_data_news_date AS C ON A.nid = C.entity_id
                WHERE TYPE = 'news'
                ORDER BY nid DESC LIMIT 0, 4";

      // get the latest notice if exists
      $results = db_query($query);
      foreach ($results as $result) {
        $nid = $result->nid;
        $title = $result->title;

        $date_array = date_parse($result->news_date_value);
        $time = mktime(0, 0, 0, $date_array['month'], $date_array['day'], $date_array['year']);
        $date = date("Y-m-d", $time); 

        $block['params'][] = array(
                              'nid' => $nid,
                              'title' => $title,
                              'date' => $date,
                            );
      }

      return $block;
    case 'noticeslist':
      $block['subject'] = t('hahah');
      $block['content'] = array('#title' => '', );
      return $block;
    case 'menu-easyloan_account':
        $block['subject'] = t('');
        $block['content'] = '';
        # code...
        break;
  }
}

function menu_account_management_capital($arg1, $arg2, $arg3){
  //return $arg1 . $arg2 . $arg3;
  return theme('account-capital', $content);
}

function menu_callback($menu, $param = ''){
  $content = array();

  switch ($menu) {
    case 'management_applications':
      return theme('management-applications', $content);
    case 'management_accountsindebt':
      if ($param=='detail'){
        return theme('management-accountsindebt-detail', $content);
      } else {
        return theme('management-accountsindebt', $content);
      }
    case 'management_loans':
      if ($param=='lend'){//intval($param) > 0) {
        return theme('management-loan-lend', $content);
      } else {
        return theme('management-loans', $content);
      }
    case 'management_withdrawappl':
      return theme('management-withdrawappl', $content);
    case 'management_investments':
      if ($param=='set'){
        return theme('management-investment-set', $content);
      } else {
        return theme('management-investments', $content);
      }
    case 'account_myinvestment':
      return theme('account-myinvestment', $content);
    case 'account_recharge':
      return theme('account-recharge', $content);
    case 'account_withdraw':
      return theme('account-withdraw', $content);
    case 'account_capital':
      return theme('account-capital', $content);
    case 'account_myloan':
      return theme('account-myloan', $content);
    case 'account_loanview':
      return theme('account-loanview', $content);
    case 'account_loanappview':
      return theme('account-loanappview', $content);
    case 'account_basicinfo':
      return theme('account-basicinfo', $content);
    case 'account_security':
      return theme('account-security', $content);
    case 'account_bankcard':
      return theme('account-bankcard', $content);
    case 'account_settings':
      return theme('account-settings', $content);
    case 'account_management':
      // check if param is a valid user id
      if (intval($param) > 0){ // user id
        // account/management/123456/capital
        // return theme('account-capital', $content);
        return theme('account-management-user', $content);
      } else {
        return theme('account-management', $content);
      }
      case 'account_management_capital':
        //return $param; // id
        return theme('account-capital', $content);

    case 'about_news':
      // check if param is a valid news id
      /*if (intval($param) > 0){
        return theme('about-news-detail', $content);
      } else {*/
        return theme('about-news', $content);
      //}
    case 'about_notices':
      // check if param is a valid notice id
      /*if (intval($param) > 0){
        return theme('about-notices-detail', $content);
      } else {*/
        return theme('about-notices', $content);
      //}
    case 'guide_guide':
      return theme('guide', $content);
    case 'guide_borrow':
      return theme('guide-borrow', $content);
    case 'guide_security':
      return theme('guide-security', $content);

    case 'help_account':
      return theme('help-account', $content);
    case 'help_intro':
      return theme('help-intro', $content);
    case 'help_fee':
      return theme('help-fee', $content);
    case 'help_borrow':
      return theme('help-borrow', $content);
    case 'help_invest':
      return theme('help-invest', $content);
    case 'help_help':
      return theme('helpcenter', $content);

    case 'borrow':
      return theme('borrow', $content);
    case 'borrow_estate':
      return theme('borrow-estate', $content);
    case 'borrow_gold':
      return theme('borrow-gold', $content);
    case 'borrow_car':
      return theme('borrow-car', $content);
    case 'borrow_credit':
      return theme('borrow-credit', $content);
    case 'borrow_else':
      return theme('borrow-else', $content); 

    case 'borrow_estate_apply':
      return theme('borrow-estate-apply', $content);
    case 'borrow_gold_apply':
      return theme('borrow-gold-apply', $content);
    case 'borrow_car_apply':
      return theme('borrow-car-apply', $content);
    case 'borrow_credit_apply':
      return theme('borrow-credit-apply', $content);
    case 'borrow_else_apply':
      return theme('borrow-else-apply', $content);
  
    case 'chinabank_send':
      return theme('chinabank-send', $content);

    default:
      # code...
      return theme('notfound', $content);
      break;
  }
}

function menu_borrow(){ return theme('borrow', array());}

function menu_notfound(){ return theme('notfound', array());}

function menu_invest($investmentid = ''){ 
  if (isset($investmentid) && is_numeric($investmentid)){
    // $content['easyloan_id'] = $investmentid; 
    return theme('invest-detail', array());
  }
  return theme('invest', array());
}

function hyd_menu_tree__menu_account_second($variables){
  return '<ul class="ui-side-sub-list">' . $variables['tree'] . '</ul>';
}

function hyd_menu_link($variables){ 
  $element = $variables['element']; 
  $sub_menu = ''; 
  
  $is_active = $element['#original_link']['in_active_trail']; 

  $element['#localized_options']['attributes']['title'] = $element['#title']; 
  
  switch ($element['#theme']) {
    case 'menu_link__easyloan_about':
    case 'menu_link__easyloan_help':
    case 'menu_link__easyloan_account':
      $node = menu_get_object();
      if ($node){
        switch ($node->type){
          case 'notice':
            if ($element['#href']=='about/notices'){
              $is_active = true;     
            }
            break;
          case 'news':
            if ($element['#href']=='about/news'){
              $is_active = true;
            }
            break;
          case 'normal':
            if(arg(0) == 'node' && is_numeric(arg(1))){
              $node = node_load(arg(1));
              if($node->title == $element['#title']){
                $is_active = true;    
              }
            }
            
            break;

          default:
            break;
        }
      }

      $depth = $element['#original_link']['depth'];
      $li_class = 'ui-side-item';

      if ($element['#below']) {
        $element['#below']['#theme_wrappers'] = array('menu_tree__menu_account_second');
        $sub_menu = drupal_render($element['#below']);
      }

      $link_style = 'ui-side-item-link'; 
      if ($depth!='1'){ 
        // sub menu 
        $link_style = 'ui-side-sub-item-link'; 
        $li_class = 'ui-side-sub-item'; 
      }

      $element['#localized_options']['attributes']['class'][] = $link_style;  
      
      $output = l($element['#title'], $element['#href'], $element['#localized_options']);

      // to fix the bug where $is_active set to false in 'user' page 
      if ((preg_match('/^user\/?\d*/', request_path()) && $element['#href']=='user')) { 
        $is_active = true; 
      }
      /*
      if ($element['#href']=='management'
        && preg_match('/^management\/\d+\/capital/', request_path())){
        $is_active = true;
      }*/
      
      $output = '<li class="' . $li_class . ' ' . ($is_active ? 'active' : '') . '">' . $output . $sub_menu . '</li>';
      return $output;

    case 'menu_link__easyloan_guide':
      $element['#localized_options']['attributes']['class'][] = 'rrd-dimgray';
      $output = l($element['#title'], $element['#href'], $element['#localized_options']);
      return '<li ' . ($is_active ? 'class="active"' : '') . '>' . $output . '</li>';

    case 'menu_link__easyloan_exchange':
      $element['#localized_options']['attributes']['class'][] = 'gray';
      $element['#localized_options']['attributes']['target'] = '_blank';
      $output = l($element['#title'], $element['#href'], $element['#localized_options']);
      return '<li class="fn-left">' . $output . '</li>';

    default:
      return theme_menu_link($variables);
      break;
  }
}

/**
* Implements hook_user_logout
*/
function easyloan_user_logout($account) { 
  // Destroy the current session, and reset $user to the anonymous user.
  session_destroy();
  drupal_goto(); 
}

function easyloan_menu_alter(&$items) {
  // the wizard registeration form menu
  $items['user/register']['page arguments'] = array('user_register_form');
  // disable the user/%/edit page to all users 
  $items['user/%user/edit']['access callback'] = 'super_admin_access';
  $items['node/%node/edit']['access callback'] = 'manager_access';
  $items['node/%node']['access callback'] = 'easyloan_node_access';
  return $items;
}

function easyloan_node_access($op, $node, $account = NULL){
  if (!$node || !in_array($op, array('view', 'update', 'delete', 'create'), TRUE)) {
    // If there was no node to check against, or the $op was not one of the
    // supported ones, we return access denied.
    return FALSE;
  }

  // If no user object is supplied, the access check is for the current user.
  if (empty($account)) {
    global $user;
    $account = $user;

    if ($user->uid ==1){
      return TRUE;
    }

    $roles = array('manager',);
    foreach ($roles as $key => $role_name) {
      if (in_array($role_name, $account->roles)) {
          return TRUE;
      }
    }
  }

  $forbidden = array();
  $forbidden[] = 'slideshow';
  $forbidden[] = 'guide';
  $forbidden[] = 'explanation';

  if (in_array($node->type, $forbidden)){
    return FALSE;
  }
  return TRUE;
}


/*
 * Only super admin can get accessed
 */
function super_admin_access() {
  global $user;
  return $user->uid == 1;
}


/*
 * Any easyloan manager can get accessed 
 */
function management_access() { 
  global $user; 
  $roles = array('auditor', 'accountant', 'manager',);

  if ($user->uid ==1){
    return TRUE;
  }

  foreach ($roles as $key => $role_name) {
    if (in_array($role_name, $user->roles)) {
        return TRUE;
    }
  }
  return FALSE;
}

/*
 * Any easyloan manager can get accessed 
 */
function manager_access() { 
  global $user; 
  if ($user->uid ==1){
    return TRUE;
  }

  $roles = array('manager',);
  foreach ($roles as $key => $role_name) {
    if (in_array($role_name, $user->roles)) {
        return TRUE;
    }
  }
  return FALSE;
}

/*
 * Any authenticated easyloan user can get accessed
 */
function authenticated_access() {
  global $user;
  return in_array("authenticated user", $user->roles);
}

function easyloan_goto($path = NULL){
  drupal_goto($path);
}

/**
 * Implements hook_views_api().
 */
function easyloan_views_api() {
  return array('api' => 3.0);
}

function easyloan_init(){
  // Set theme's path
  $themepath = drupal_get_path('theme', 'hyd');
  // add theme css in group CSS_SYSTEM
  drupal_add_css($themepath . '/css/one.css', 
    array('group' => CSS_SYSTEM, 'type' => 'file', 'weight' => -100));
}


function easyloan_changeimg_form($form, &$form_state) {
  global $user;
  if (!$user->uid) {
    return array();
  }

  module_load_include('inc', 'user', 'user.pages');

  // get the default user form so we can reuse
  // the validation and submit stuff
  // then use hook_form_FORM_ID_alter to remove everything
  // but the picture field
  $form = user_profile_form($form, $form_state, $user);

  // grab the picture field (which may have been nested if field_group is installed)
  $fpic = easyloan_picture_field($form);
  if (!$fpic) {
    // no picture field here
    watchdog('profile_pic_changer', 'Error finding picture field in the profile form.', WATCHDOG_ERROR);
    return array();
  }

  // unset anything that isn't the Save button
  foreach ($form as $k => $v) {
    // internal keys
    if (substr($k, 0, 1) == '#') {
      continue;
    }

    // the save button
    if ($k == 'actions') {
      continue;
    }

    // other important fields
    if (substr($k, 0, 4) == 'form') {
      continue;
    }

    unset($form[$k]);
  }

  // add the pic field back
  $form['picture'] = $fpic;

  // pull validation on everything except our picture field
  $form['#validate'] = array('user_validate_picture');

  return $form;
}

/**
 * Retrieve the picture field only
 *
 * @param $element
 *
 * @return
 * An array describing the picture field
 */
function easyloan_picture_field($element) {
  foreach ($element as $k => $v) {
    if ($k == 'picture' && is_array($v)) {
      return $element[$k];
    }

    if (is_array($element[$k])) {
      $test = easyloan_picture_field($element[$k]);
      if ($test) {
        return $test;
      }
    }
  }

  return NULL;
}

function easyloan_user_login(&$edit, $account) {
  module_load_include('php', 'easyloan', 'api/sys_user');
  set_user(2, $account->uid);
/*
  // we can't set drupal_goto here, because it will 
  // interrupt the registering form from submitting
  drupal_goto("user/" . $account->uid);
*/
}

function easyloan_user_register_submit(&$form, &$form_state) { 
  // The password is in $form_state['values']['pass'].
  $pass = $form_state['values']['pass'];
  $name = $form_state['values']['name'];

  global $user;
  module_load_include('php', 'easyloan', 'api/sys_user');
  set_user(1, $user->uid, $name . ';' . $pass);
  
  module_load_include('php', 'easyloan', 'api/util_initialize_user');
  initialize_user($user->uid);
}

function easyloan_form_alter(&$form, &$form_state, $form_id) { 
  if($form_id == 'user_register_form'){ 
    // the following code doesn't work here 
    $form['#submit'][] = 'easyloan_user_register_submit';

    $tag = time() . '_' . rand(1000,9999); 
    $form['account']['mail']['#value'] = $tag . '@a.com'; // set to a fake value to cheat the validation for email 
  } 
}